name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install

      - name: Patch Podfile for FFmpeg
        run: |
          # Inyectar la versión funcional de ffmpeg-kit directamente en el Podfile
          sed -i '' "s/target 'cuteNTR' do/target 'cuteNTR' do\n  pod 'ffmpeg-kit-ios-https', '5.1'/g" ios/Podfile

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS Workspace
        working-directory: ios
        run: |
          xcodebuild -workspace cuteNTR.xcworkspace \
                     -scheme cuteNTR \
                     -sdk iphoneos \
                     -configuration Release \
                     -derivedDataPath ../build \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO

      - name: Package to .IPA
        run: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r cuteNTR.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cuteNTR-ipa
          path: cuteNTR.ipa
